# This file is automatically managed by gotoni
# It contains the SSH key name for the most recently launched instance
# You don't need to create or edit this file manually

lambda-key-1736012345                      